name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ec2-user
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -i key.pem $EC2_USER@$EC2_HOST "docker pull yourdockerhubusername/yourrepositoryname:latest"
          ssh -i key.pem $EC2_USER@$EC2_HOST "docker stop my-stopwatch-app || true"
          ssh -i key.pem $EC2_USER@$EC2_HOST "docker rm my-stopwatch-app || true"
          ssh -i key.pem $EC2_USER@$EC2_HOST "docker run -d -p 80:8080 --name my-stopwatch-app yourdockerhubusername/yourrepositoryname:latest"
          rm key.pem
